### ISSUE TITLE
Linux: double free or corruption

### ISSUE THREAD

**Issue by d33psky** [OpenPHDGuiding/phd2#465]
brain->guiding-> search region 25 pixels (with stock 15 pixels the simulator looses the star at step)
connect camera simulator
connect on-camera mount simulator
connect ao simulator
loop
auto-select star
begin guiding

After a few seconds : 
```gdb
(gdb) run
Starting program: /home/hans/src/.phd2/phd2 
Traceback (most recent call last):
  File "/usr/share/gdb/auto-load/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19-gdb.py", line 63, in <module>
    from libstdcxx.v6.printers import register_libstdcxx_printers
ImportError: No module named 'libstdcxx'
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffebcfe700 (LWP 21407)]
[New Thread 0x7fffeb4fd700 (LWP 21408)]
[New Thread 0x7fffea375700 (LWP 21409)]
[New Thread 0x7fffe9b74700 (LWP 21410)]
[New Thread 0x7fffe9373700 (LWP 21411)]
[New Thread 0x7fffe8b72700 (LWP 21412)]
[Thread 0x7fffe9373700 (LWP 21411) exited]
(phd2:21387): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to allocate widget with width -5 and height 17
(phd2:21387): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to allocate widget with width -5 and height 17
(phd2:21387): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to allocate widget with width -5 and height 17
(phd2:21387): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to allocate widget with width -5 and height 17
(phd2:21387): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to allocate widget with width -5 and height 17
(phd2:21387): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to allocate widget with width -5 and height 17
[Thread 0x7fffe8b72700 (LWP 21412) exited]
[New Thread 0x7fffe8b72700 (LWP 21512)]
[Thread 0x7fffe8b72700 (LWP 21512) exited]
*** Error in `/home/hans/src/.phd2/phd2': double free or corruption (fasttop): 0x00007fffe40d75b0 ***
Program received signal SIGABRT, Aborted.
0x00007ffff4850cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56      ../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
```

```bt
(gdb) bt
#0  0x00007ffff4850cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff48540d8 in __GI_abort () at abort.c:89
#2  0x00007ffff488d394 in __libc_message (do_abort=do_abort@entry=1, fmt=fmt@entry=0x7ffff499bb28 "*** Error in `%s': %s: 0x%s ***\n")
    at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007ffff489966e in malloc_printerr (ptr=<optimized out>, str=0x7ffff499bcf0 "double free or corruption (fasttop)", action=1) at malloc.c:4996
#4  _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:3840
#5  0x00007ffff392a437 in gdk_region_union () from /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
#6  0x00007ffff3934b6d in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
#7  0x00007ffff3934cab in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
#8  0x00007ffff70026f3 in wxWindow::Refresh(bool, wxRect const*) () from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_unofficial_core-3.0.so.0
#9  0x00007ffff7035678 in wxStatusBar::DoUpdateStatusText(int) () from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_unofficial_core-3.0.so.0
#10 0x00000000005cb6a5 in MyFrame::OnSetStatusText (this=0xc2d3a0, event=...) at /home/hans/src/phd2/myframe.cpp:1111
#11 0x00007ffff69302ae in wxAppConsoleBase::CallEventHandler(wxEvtHandler*, wxEventFunctor&, wxEvent&) const ()
   from /usr/lib/x86_64-linux-gnu/libwx_baseu_unofficial-3.0.so.0
#12 0x00007ffff6aa3392 in wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) ()
   from /usr/lib/x86_64-linux-gnu/libwx_baseu_unofficial-3.0.so.0
#13 0x00007ffff6aa3443 in wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*) () from /usr/lib/x86_64-linux-gnu/libwx_baseu_unofficial-3.0.so.0
#14 0x00007ffff6aa379d in wxEvtHandler::TryHereOnly(wxEvent&) () from /usr/lib/x86_64-linux-gnu/libwx_baseu_unofficial-3.0.so.0
#15 0x00007ffff6aa3813 in wxEvtHandler::ProcessEventLocally(wxEvent&) () from /usr/lib/x86_64-linux-gnu/libwx_baseu_unofficial-3.0.so.0
#16 0x00007ffff6aa3875 in wxEvtHandler::ProcessEvent(wxEvent&) () from /usr/lib/x86_64-linux-gnu/libwx_baseu_unofficial-3.0.so.0
#17 0x00007ffff6aa48a3 in wxEvtHandler::ProcessPendingEvents() () from /usr/lib/x86_64-linux-gnu/libwx_baseu_unofficial-3.0.so.0
#18 0x00007ffff6933e77 in wxAppConsoleBase::ProcessPendingEvents() () from /usr/lib/x86_64-linux-gnu/libwx_baseu_unofficial-3.0.so.0
#19 0x00007ffff6fd6022 in wxApp::DoIdle() () from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_unofficial_core-3.0.so.0
#20 0x00007ffff6fd6133 in ?? () from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_unofficial_core-3.0.so.0
#21 0x00007ffff2a61ce5 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#22 0x00007ffff2a62048 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#23 0x00007ffff2a6230a in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#24 0x00007ffff3cd5447 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#25 0x00007ffff6fe8f05 in wxGUIEventLoop::DoRun() () from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_unofficial_core-3.0.so.0
#26 0x00007ffff6972b30 in wxEventLoopBase::Run() () from /usr/lib/x86_64-linux-gnu/libwx_baseu_unofficial-3.0.so.0
#27 0x00007ffff693238d in wxAppConsoleBase::MainLoop() () from /usr/lib/x86_64-linux-gnu/libwx_baseu_unofficial-3.0.so.0
#28 0x00007ffff69be49d in wxEntry(int&, wchar_t**) () from /usr/lib/x86_64-linux-gnu/libwx_baseu_unofficial-3.0.so.0
#29 0x00000000005e8566 in main (argc=1, argv=0x7fffffffdc88) at /home/hans/src/phd2/phd.cpp:68
```

OnSetStatus looks fine to me : 
```
(gdb) up 10
#10 0x00000000005cb6a5 in MyFrame::OnSetStatusText (this=0xc2d3a0, event=...) at /home/hans/src/phd2/myframe.cpp:1111
1111            wxFrame::SetStatusText(msg, pane);
(gdb) list
1106
1107        if (pane == 1)
1108        {
1109            // display message for 2.5s, or until the next message is displayed
1110            const int DISPLAY_MS = 2500;
1111            wxFrame::SetStatusText(msg, pane);
1112            m_statusbarTimer.Start(DISPLAY_MS, wxTIMER_ONE_SHOT);
1113        }
1114        else
1115        {
(gdb) p msg
$1 = {static npos = 18446744073709551615, m_impl = {static npos = 18446744073709551615, 
    _M_dataplus = {<std::allocator<wchar_t>> = {<__gnu_cxx::new_allocator<wchar_t>> = {<No data fields>}, <No data fields>}, 
      _M_p = 0x7fffe40d6ef8 L"West  0.35 px   4 ms          North 0.62 px 8 ms"}}, m_convertedToChar = {m_str = 0x0, m_len = 140737488344848}}
```

git master branch head (git show -> 647b04994800977d77cf839c1cfb35d840b8a3fc)
ubuntu 14.04
wx3.0.2 (from http://codelite.org/LiteEditor/WxWidgets30Binaries#toc2 repo) , same results with stock wx3.0.0

**Comment by agalasso** [comment]
we believe this was fixed by ensuring that all wx UI calls are from the main thread
